start = expression

expression = (whitespace / comment)* e:(atom / exprlist / quote) (whitespace / comment)*
                {return e;}
                
validchar = [0-9a-zA-Z_?!+=@#$%^&*/.|><-]

atom = num:[0-9]+ { return +num.join(""); } /
       chars:validchar+ { return chars.join(""); }

exprlist = "(" e:(expression)* ")"
        { return e; }

whitespace = [ \t\n\r]

quote = "'" e:expression
        { return ["quote", e]; }

comment = ';;' [^\n\r]*